// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'gptbanqbusiness';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String PAYMENT = 'assets/profile/payment.png';
  static const String WALLET_TRANSFER = 'assets/svg/wallet-transfer.svg';
}
