// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMEowGVgFZ4UMqeHonzTM037_WF8O1SSI',
    appId: '1:658122776500:web:23112286064af218369ce1',
    messagingSenderId: '658122776500',
    projectId: 'gptbanqbusiness',
    authDomain: 'gptbanqbusiness.firebaseapp.com',
    storageBucket: 'gptbanqbusiness.appspot.com',
    measurementId: 'G-S2EKVL06LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-dkCgqbGY1FjmUGdpBQ8SF3vVBQ8PVyc',
    appId: '1:1023663653773:android:b5a2af1abcf32671cdf3c4',
    messagingSenderId: '1023663653773',
    projectId: 'gptbanq-business',
    storageBucket: 'gptbanq-business.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZR7vhD3YibiGwRyhnQVtCxZw1HP8dF08',
    appId: '1:1023663653773:ios:2e1d75cb97c152d7cdf3c4',
    messagingSenderId: '1023663653773',
    projectId: 'gptbanq-business',
    storageBucket: 'gptbanq-business.firebasestorage.app',
    iosBundleId: 'com.gptbanq.business',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH1L1zmVGR0KlPmU63QhMgqAzA0nJYLnM',
    appId: '1:658122776500:ios:8ac6f663997d374b369ce1',
    messagingSenderId: '658122776500',
    projectId: 'gptbanqbusiness',
    storageBucket: 'gptbanqbusiness.appspot.com',
    iosBundleId: 'com.example.coxibussines.RunnerTests',
  );
}